### PR TITLE
add conda install with cla

### PR DESCRIPTION
**Pull request by rpanai**

### CODE REVIEW

**Comment by gwenzek** [comment]
Thanks for doing this.
What's the plan to keep the conda package uptodate with the pypi package ?
Is it done automatically ?
If the conda packaging fail, how would we know ?

Could you add a description to the conda page: https://anaconda.org/conda-forge/submitit ?
Ideally the Readme should be displayed there.

Could you also add the following badges at the top of the Readme ?

[Pypi](https://pypi.org/project/submitit/)
[Conda](https://anaconda.org/conda-forge/submitit)

```
[![Pypi](https://img.shields.io/pypi/v/submitit)](https://pypi.org/project/submitit/)
[![conda-forge](https://img.shields.io/conda/vn/conda-forge/submitit)](https://anaconda.org/conda-forge/submitit)
```

**Review by gwenzek — CHANGES_REQUESTED** [review]
Could you also add the following badges at the top of the Readme ?

[Pypi](https://pypi.org/project/submitit/)
[Conda](https://anaconda.org/conda-forge/submitit)

```
[![Pypi](https://img.shields.io/pypi/v/submitit)](https://pypi.org/project/submitit/)
[![conda-forge](https://img.shields.io/conda/vn/conda-forge/submitit)](https://anaconda.org/conda-forge/submitit)
```

**Comment by rpanai** [comment]
> Thanks for doing this.
> What's the plan to keep the conda package uptodate with the pypi package ?
> Is it done automatically ?
> If the conda packaging fail, how would we know ?
> 
> Could you add a description to the conda page: https://anaconda.org/conda-forge/submitit ?
> Ideally the Readme should be displayed there.

**Comment by rpanai** [comment]
> Thanks for doing this.
> What's the plan to keep the conda package uptodate with the pypi package ?
> Is it done automatically ?
> If the conda packaging fail, how would we know ?
> 
> Could you add a description to the conda page: https://anaconda.org/conda-forge/submitit ?
> Ideally the Readme should be displayed there.

I think I did some mess with this and I added a new [PR](https://github.com/facebookincubator/submitit/pull/21) with the requested badges. 
> Is it done automatically ?
Yes
> If the conda packaging fail, how would we know ?
the maintainers of that recipe are going to receive a mail if something fail. I can add maintainers as i did for [hiplot](https://github.com/conda-forge/hiplot-feedstock)

**Pull request closed without merging**
