### PR TITLE
[To be discussed] Add option to submit within a batch context

### PR DESCRIPTION
**Pull request by jrapin**
the aim is to be automatically batch jobs which can be batched together, but submit whenever we need information:
Eg: in nevergrad we send 40 jobs for evaluation, which could be packed together, and then whenever a job is finished we reschedule a new evaluation. Currently it's impossible to do with a batch context (or any other option), but with this change, it would be possible, by running the optimization within a batch context. This way initial submissions are packed, and sent whenever we start checking there status.

### CODE REVIEW

**Comment by gwenzek** [comment]
I'm not fond of this kind of implicit behavior. If you want a job to be submitted, don't  "access an attribute inside a context", just submitit :-) 

What kind of code would be made simpler by this code ?

**Comment by jrapin** [comment]
> What kind of code would be made simpler by this PR ?

It's not making thinks simpler but making things possible to batch jobs whenever possible, while it would not be before. For instance with nevergrad it becomes possible to do:

```python
with executor.batch(allow_implicit_submission=True):
    optimizer.minimize(func, executor=executor)
```
This would not be possible before because minimize schedules a bunch of jobs at a time (which should preferably be done with mapping), then waits for one (or several) to be done (so accesses the done() method which accesses some attributes) before scheduling new one(s). A very simplified version is something like this:

```python
running = []
with executor.batch(allow_implicit_submission=True):
    while True:
        while len(running) <= 40:
            running.append(executor.submit(func))
        running = [j for j in running if not j.done()]
        time.sleep(1)
```

With this PR, any job that can be packed together will be packed together, without requiring to add any explicit dependency to submitit since the batch context remains external. This allows to keep accepting both concurrent.futures executors and submitit executors easily.

**Comment by timlacroix** [comment]
I don't have any problems with the functionality. I imagine the worry is that users might mess up batching altogether by mistakenly accessing attributes inside the context. Maybe an optional warning (present by default) if jobs are being submitted one by one ?  

Regarding testing, I'd add a test that things are indeed batched f they can be (I think for now the only thing being tested is that they are submitted inside the context). Maybe with code that looks like your example above ?

**Comment by gwenzek** [comment]
dropped in favor of #1676

**Pull request closed without merging**
