### PR TITLE
add submit_array for submitting an list of checkpointable

### PR DESCRIPTION
**Pull request by gwenzek**
@jrapin this will allow to submit an array of Checkpointable.
This is one of the pain point raised by @louismartin  IIRC.

### CODE REVIEW

**Comment by louismartin** [comment]
Yes that's great thanks !
And there's no way to have the same thing but with arguments? Just asking without conviction because it will probably make the input signature more opaque.

**Comment by jrapin** [comment]
> Yes that's great thanks !
> And there's no way to have the same thing but with arguments? Just asking without conviction because it will probably make the input signature more opaque.

they way to have it with arguments is to use the context manager.
I still prefer the context manager by far :D I'm not found of adding yet another submission API, but your call ;)

**Comment by louismartin** [comment]
> > Yes that's great thanks !
> > And there's no way to have the same thing but with arguments? Just asking without conviction because it will probably make the input signature more opaque.
> 
> they way to have it with arguments is to use the context manager.
> I still prefer the context manager by far :D I'm not found of adding yet another submission API, but your call ;)

Oh yes my bad, I thought that this PR was made for submitting multiple checkpointable in a single job without having to use function sequence, forget what I said.
I always use the context manager !

**Comment by gwenzek** [comment]
>  I'm not found of adding yet another submission API

@jrapin If you look at the code all the submission API uses the same underlying method:
`self._internal_process_submissions(submissions)`

Should we expose this instead ?
Overall I don't understand why we need both Checkpointable and DelayedFunction.
`.batch()` and `.map_array` are only helpers to create `DelayedFunction` from raw function or `Checkpointable`

**Comment by gwenzek** [comment]
Merging this for now as it's too useful to pass by.
It can be use to submit a function with arguments as shown in the docstring.

**Pull request merged**
