### PR TITLE
Reuse sigusr1 for preemption and timeout (#1615 rollback)

### PR DESCRIPTION
**Pull request by jrapin**

### CODE REVIEW

**Comment by gwenzek** [comment]
Why so many commits ? Isn't this "just" a `git revert 6309444ff1c0f1c6eabe33eb8f86c11ad01aa2e2` ?

**Comment by jrapin** [comment]
> Why so many commits ? Isn't this "just" a `git revert 6309444ff1c0f1c6eabe33eb8f86c11ad01aa2e2` ?

6309444ff1c contains more stuff (integration tests, some renaming etc) so it's a manual curated revert (+ displaying actual signal name instead of number)

**Comment by jrapin** [comment]
Looks like it works
```
submitit INFO (2021-04-01 01:25:50,621) - Starting with JobEnvironment(job_id=39025082, hostname=learnfair4096, local_rank=0(1), node=0(1), global_rank=0(1))
submitit INFO (2021-04-01 01:25:50,621) - Loading pickle: /private/home/jrapin/fairinternal/submitit_jr/outputs/preempt_logs/39025082_submitted.pkl
now: 2021-04-01 01:25:50.625474
now: 2021-04-01 01:26:50.685580
now: 2021-04-01 01:27:50.74609
...
now: 2021-04-01 02:21:53.829307
now: 2021-04-01 02:22:53.889414
now: 2021-04-01 02:23:53.949538
now: 2021-04-01 02:24:54.009634
now: 2021-04-01 02:25:54.069715
submitit WARNING (2021-04-01 02:26:27,643) - Bypassing signal SIGCONT
submitit INFO (2021-04-01 02:26:27,643) - Job has not timed out. Ran 61 minutes out of requested 120 minutes.
submitit WARNING (2021-04-01 02:26:27,643) - Caught signal SIGUSR1 on learnfair4096: this job is preempted.
submitit INFO (2021-04-01 02:26:28,004) - Requeued job 39025082 (3 remaining timeouts)
submitit INFO (2021-04-01 02:26:28,004) - Exiting gracefully after preemption/timeout.
submitit INFO (2021-04-01 02:33:01,844) - Starting with JobEnvironment(job_id=39025082, hostname=learnfair4006, local_rank=0(1), node=0(1), global_rank=0(1))
submitit INFO (2021-04-01 02:33:01,844) - Loading pickle: /private/home/jrapin/fairinternal/submitit_jr/outputs/preempt_logs/39025082_submitted.pkl
now: 2021-04-01 02:33:01.848230
now: 2021-04-01 02:34:01.899404
now: 2021-04-01 02:35:01.959918
now: 2021-04-01 02:36:02.020380
now: 2021-04-01 02:37:02.080820
...
now: 2021-04-01 04:28:08.388799
now: 2021-04-01 04:29:08.392776
now: 2021-04-01 04:30:08.452889
now: 2021-04-01 04:31:08.513033
submitit INFO (2021-04-01 04:31:14,047) - Job has timed out. Ran 118 minutes out of requested 120 minutes.
submitit WARNING (2021-04-01 04:31:14,047) - Caught signal SIGUSR1 on learnfair4006: this job is timed-out.
submitit INFO (2021-04-01 04:31:14,047) - Job not requeued because: timed-out and not checkpointable.
submitit ERROR (2021-04-01 04:31:14,060) - Submitted job triggered an exception
```

**Comment by jrapin** [comment]
@gwenzek should I bump the version to 1.3.1?

**Review by gwenzek — APPROVED** [review]
Goods for me, please also bump the version number and mention clearly the previous commit in this commit message :-)

**Comment by gwenzek** [comment]
This PR is a rollback of #1615 .
`SIGTERM` is also used for OOM and by `scancel`. We can't use it for preemption. Fundamentally this make submitit requires the cluster to have `preempt_send_user_signal`

**Pull request merged**
